import "./globals.css";

export const metadata = {
  title: "Jungbir Singh Hanspal",
  //description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
